//Next JS imports
import Head from "next/head";

//React import
import { useState, useEffect } from "react";

//Near imports
import { signIn, signOut, wallet, get_nft } from "../near/near-setup";

export default function Home() {
  const [user, setUser] = useState(null);
  const [nfts, setNfts] = useState('')

  useEffect(() => {
    if (wallet.getAccountId()) {
      setUser(wallet.getAccountId());
    }

    const getNft = async () => {
      const res = await get_nft()
      setNfts(res)
    }

    getNft()
  }, []);

  const nftOld = () => {
    get_nft_old()
  }
  return (
    <div>
      <Head>
        <title>Next JS-Near Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main-div">
        {!user ? (
          <>
            <h4>This is a Near Api template for Next JS</h4>
            <button
              className="button"
              onClick={() => {
                signIn();
              }}
            >
              Sign In
            </button>
          </>
        ) : (
          <>
            <h4>Welcome {user}</h4>
            {nfts}
            <button
              className="button"
              onClick={() => {
                signOut();
                setUser(null);
              }}
            >
              Sign out
            </button>
          </>
        )}
      </div>
    </div>
  );
}
